HomeWork about deeplinks and notifications
ermac95/MyCodeFlowAcademyProject pull request #9
Opened 2021-02-14 20:09 UTC by ermac95

2021-02-15 06:20 UTC, webanimal requested changes

2021-02-15 06:20 UTC, webanimal commented on app/src/main/AndroidManifest.xml
> +    package="com.mycodeflow.ui">
Package name так просто у проекта нельзя переименовать. Это надо очень аккуратно делать. Т.к. это не только имя, но и структура папок, и структура зависимостей.
Проверяй также `build.gradle` файлы, и прочие импорты.
Так же ссылки на `tools:context=""` в лэйаутах.
Попробуй пооткрывать все файлы и убедиться, что они не показывают ошибку зависимостей.
Потом очисти проект, очисти и инвалидируй кеш студии, потом перезапусти студию и пересобири проект заново.

2021-02-15 06:20 UTC, webanimal commented on app/src/main/java/com/mycodeflow/utils/MovieUpdateNotification.kt
> +        PendingIntent.getActivity(context, 1, openDetailIntent, PendingIntent.FLAG_UPDATE_CURRENT)
Что такое `1`?

2021-02-15 06:20 UTC, webanimal commented on app/src/main/java/com/mycodeflow/utils/MovieUpdateNotification.kt
> +                .setContentTitle("A new movie found")
Лучше вынести в ресурсы. Это же не временный текст, это заголовок нотификаций.

2021-02-15 06:20 UTC, webanimal commented on app/src/main/java/com/mycodeflow/utils/MovieUpdateNotification.kt
> +        const val NOTIFICATION_ID = 1
Не знаю, как ты хотел по логике, но у тебя не уникальный айдишник. Может так и надо, а может нет. Обращаю внимание.

2021-02-15 06:20 UTC, webanimal commented on app/src/main/java/com/mycodeflow/work/CacheUpdateWork.kt
>              return Result.retry()
Может в бесконечный цикл войти, а когда ты начинаешь часто падать в бэкграунде b ;hfnm htcehcs, тебя начинают помещать во всякие игноры, черные списки и понижают приоритет и "надежность" приложения на девайсе.
Также, если пропал интернет, вряд ли он прям сразу появится.
Поэтому лучше перепланировать работу, а не retry.

Я точно не помню, но вроде HttpException, это только один из нескольких вариантов ошибок соединения.
Но все они вроде наследуются от IoException. Лучше ловить его.

2021-02-15 16:54 UTC, ermac95 commented on app/src/main/java/com/mycodeflow/utils/MovieUpdateNotification.kt
> +        PendingIntent.getActivity(context, 1, openDetailIntent, PendingIntent.FLAG_UPDATE_CURRENT)
Это реквест код, так как у нас на текущий момент одно такое уведомление, я поставил единицу. Если вопрос на знание зачем нужен реквест код, то он нужен для того, чтобы различать наши PendingIntent, и если что изменять его обработку в зависимости от данного кода

2021-02-15 17:31 UTC, webanimal commented on app/src/main/java/com/mycodeflow/utils/MovieUpdateNotification.kt
> +        PendingIntent.getActivity(context, 1, openDetailIntent, PendingIntent.FLAG_UPDATE_CURRENT)
Это был толстый намёк, что надо в "говорящие" константы запихивать волшебные числа.

2021-02-15 17:39 UTC, webanimal requested changes

2021-02-15 17:39 UTC, webanimal commented on app/src/main/java/com/mycodeflow/work/CacheUpdateWork.kt
>              return Result.retry()
- [ ] У тебя catch срабатывает тогда, когда `coroutineScope` уже не активет, т.к. сначала выкинулась ошибка, потом coroutineScope отменился, а потом ты эт опоймал. Перенеси `try-catch` внуть корутины.
- [ ] Замени ретрай. Или добавь таймауты - т.й. сохраняй хотябы в преференсах таймер последней попытки, номер попытки реконнекта. Добавь массив таймаутов, как я в чате группы написал. В случае успеха - сбрасывай счётчик "не удачных" попыток. Ну или убери ретрай)

2021-02-17 13:43 UTC, ermac95 reviewed
Здесь все исправлено

2021-02-17 13:43 UTC, ermac95 commented on app/src/main/java/com/mycodeflow/utils/MovieUpdateNotification.kt
> +                .setContentTitle("A new movie found")
Пофиксил

2021-02-17 13:43 UTC, ermac95 commented on app/src/main/java/com/mycodeflow/utils/MovieUpdateNotification.kt
> +        const val NOTIFICATION_ID = 1
Изменил

2021-02-17 13:43 UTC, ermac95 commented on app/src/main/java/com/mycodeflow/work/CacheUpdateWork.kt
>              return Result.retry()
Пофиксил через ограничение попыток в worker, а также через установку backOffPolicy при создании задачи

2021-02-17 13:43 UTC, ermac95 commented on app/src/main/java/com/mycodeflow/utils/MovieUpdateNotification.kt
> +        PendingIntent.getActivity(context, 1, openDetailIntent, PendingIntent.FLAG_UPDATE_CURRENT)
Пофиксил

2021-02-17 13:45 UTC, ermac95 commented on app/src/main/java/com/mycodeflow/work/CacheUpdateWork.kt
>              return Result.retry()
Занес try/catch в coroutine, с ретрай решил строенными средствами путем backOffPolicy(timeout intervals) and runAttemptCount(counter for the number of allowed attempts)

2021-02-21 04:31 UTC, webanimal approved these changes

2021-02-21 04:35 UTC, webanimal approved these changes

2021-02-21 04:35 UTC, webanimal commented on .idea/misc.xml
>  <?xml version="1.0" encoding="UTF-8"?>
У тебя через `.gitignore` пролез какой-то не нужный файл.

2021-02-21 04:35 UTC, webanimal commented on app/src/main/java/com/mycodeflow/utils/MovieUpdateNotification.kt
> +        PendingIntent.getActivity(context, 7773568, openDetailIntent, PendingIntent.FLAG_UPDATE_CURRENT)
Не уверен, но глянь: что это за число, разве здесь не должна быть константа `NOTIFICATION_ID`? Если нет, то это тоже надо будет вынести в `Именованные` константы.

2021-02-21 04:35 UTC, webanimal commented on app/src/main/java/com/mycodeflow/work/CacheUpdateWork.kt
> +        if (runAttemptCount > 3){
Тоже в именованные константы, или переменную.
Это правильная практика, поэтому я это везде и пишу тебе.

2021-02-21 12:08 UTC, ermac95 commented on app/src/main/AndroidManifest.xml
> +    package="com.mycodeflow.ui">
Все чекнул, ошибок нет

2021-02-21 12:10 UTC, merged